version: 1.0.{build}

# Gradle 3.1 does not support the Visual Studio 2015 include folder structure,
#   so we fall back to VS 2013.
image: Visual Studio 2013

build_script:
- cmd: gradlew.bat classes

test_script:
- cmd: gradlew.bat check